"""Compatibility re-exports. Dataset slicing lives in ``dataset_processor``.

    attacker extract --evtx sysmon.evtx --pcap mixed.pcapng --out-dir out
    python -m dataset_processor --evtx sysmon.evtx --pcap mixed.pcapng --out-dir out
"""

from __future__ import annotations

from dataset_processor.cli import add_extract_parser
from dataset_processor.extract import (
    ATTACK_IMAGES,
    DEFAULT_EXCLUDE_FLOWS,
    DEFAULT_LAB_NETS,
    ExcludeFlow,
    ExtractOptions,
    NetworkConnect,
    PacketRow,
    ProcessCreate,
    SCAN_TECHNIQUES,
    SelectedConnect,
    TSHARK_FIELDS,
    assert_output_not_source,
    attacker_ip_from_config,
    auto_unlogged_scan,
    build_display_filter,
    build_window_query,
    connection_is_malicious,
    dump_tshark_fields,
    exclude_flows_from_config,
    export_evtx_window,
    export_task_evtx_files,
    extract_from_sources,
    flow_is_excluded,
    image_basename,
    infer_attacker_ip,
    ip_in_nets,
    lab_nets_from_config,
    list_task_transcripts,
    load_sysmon_events,
    match_streams,
    merge_pcaps,
    options_from_args,
    parse_networks,
    parse_sysmon_xml,
    parse_task_window,
    parse_technique_id,
    parse_tshark_fields,
    peer_ips_from_exclude_flows,
    processes_by_guid,
    resolve_day_logs_dir,
    resolve_extract_out_dir,
    run_extract,
    run_extract_batch,
    select_malicious_connects,
    selected_to_records,
    utc_query_bound,
    write_filtered_pcap,
    write_pcap_from_filters,
    apply_task_txt_filter,
    load_task_display_filter,
    task_filter_is_forbidden,
    time_window_display_filter,
)
from dataset_processor.paths import technique_pcap_stem

__all__ = [
    "ATTACK_IMAGES",
    "DEFAULT_EXCLUDE_FLOWS",
    "DEFAULT_LAB_NETS",
    "ExcludeFlow",
    "ExtractOptions",
    "NetworkConnect",
    "PacketRow",
    "ProcessCreate",
    "SCAN_TECHNIQUES",
    "SelectedConnect",
    "TSHARK_FIELDS",
    "add_extract_parser",
    "assert_output_not_source",
    "attacker_ip_from_config",
    "auto_unlogged_scan",
    "build_display_filter",
    "build_window_query",
    "connection_is_malicious",
    "dump_tshark_fields",
    "exclude_flows_from_config",
    "export_evtx_window",
    "export_task_evtx_files",
    "extract_from_sources",
    "flow_is_excluded",
    "image_basename",
    "infer_attacker_ip",
    "ip_in_nets",
    "lab_nets_from_config",
    "list_task_transcripts",
    "load_sysmon_events",
    "match_streams",
    "merge_pcaps",
    "options_from_args",
    "parse_networks",
    "parse_sysmon_xml",
    "parse_task_window",
    "parse_technique_id",
    "parse_tshark_fields",
    "peer_ips_from_exclude_flows",
    "processes_by_guid",
    "resolve_day_logs_dir",
    "resolve_extract_out_dir",
    "run_extract",
    "run_extract_batch",
    "select_malicious_connects",
    "selected_to_records",
    "technique_pcap_stem",
    "utc_query_bound",
    "write_filtered_pcap",
    "write_pcap_from_filters",
    "apply_task_txt_filter",
    "load_task_display_filter",
    "task_filter_is_forbidden",
    "time_window_display_filter",
]
