#!/usr/bin/env python3
"""Create or update daily task JSON, and dispatch a task to soldier (single-line JSON over TCP)."""

from __future__ import annotations

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

import argparse
import configparser
import json
import socket
import uuid
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import Any

import logging
import logging.handlers

from common import validate_task_id
from repository import DailyTaskRepository


DEFAULT_CONFIG_NAME = "commander.ini"


def default_config_path() -> Path:
    """Return default config file path (same directory as script)."""
    return Path(__file__).resolve().parent / DEFAULT_CONFIG_NAME


def load_target_config(config_path: Path, target: str) -> tuple[str, int]:
    """
    Load host and port for a target from INI config file.
    
    Raises:
        ValueError: if config file not found or target not defined
        FileNotFoundError: if config file does not exist
    """
    if not config_path.is_file():
        raise FileNotFoundError(f"Config file not found: {config_path}")
    
    cp = configparser.ConfigParser()
    cp.read(config_path, encoding="utf-8")
    
    # Target must be lowercase for strict matching
    target_lower = target.lower()
    
    if target_lower not in cp:
        raise ValueError(f"Target '{target}' not defined in config file {config_path}")
    
    sec = cp[target_lower]
    host = (sec.get("host") or "").strip()
    port_str = (sec.get("port") or "").strip()
    
    if not host:
        raise ValueError(f"Target '{target}' missing 'host' in config file")
    if not port_str:
        raise ValueError(f"Target '{target}' missing 'port' in config file")
    
    try:
        port = int(port_str)
        if not 1 <= port <= 65535:
            raise ValueError(f"Invalid port {port} for target '{target}', must be 1-65535")
    except ValueError as e:
        raise ValueError(f"Invalid port '{port_str}' for target '{target}': {e}")
    
    return host, port


def has_waiting_tasks(repository: DailyTaskRepository, date_str: str, role: str) -> bool:
    """Check role-scoped waiting tasks through repository."""
    return repository.has_active_waiting_task(role, date_str)


def append_task(
    repository: DailyTaskRepository,
    date_str: str,
    role: str,
    task_id: str,
    task_text: str,
    expiry_time: str,
    planned_time: str | None = None,
) -> None:
    repository.bind_dispatched_task(
        date_str=date_str,
        role=role,
        task_id=task_id,
        task_text=task_text,
        expiry_time=expiry_time,
        planned_time=planned_time,
    )


def send_to_soldier(
    soldier_host: str,
    soldier_port: int,
    task_ref: str,
    command: str,
    task_date: str,
    planned_time: str | None = None,
    timeout: float = 120.0,
) -> dict[str, Any]:
    payload = {
        "task_ref": task_ref,
        "command": command,
        "task_date": task_date,
        "planned_time": planned_time,
    }
    line = json.dumps(payload, ensure_ascii=False) + "\n"
    try:
        with socket.create_connection((soldier_host, soldier_port), timeout=timeout) as sock:
            sock.sendall(line.encode("utf-8"))
            logging.info(f"Task {task_ref} dispatched to {soldier_host}:{soldier_port}")
    except OSError as e:
        logging.error(f"Failed to dispatch task {task_ref}: {e}")
        return {"ok": False, "error": f"Connection failed: {e}"}
    return {"ok": True}


def main() -> int:
    p = argparse.ArgumentParser(description="Write daily task file and dispatch command to soldier")
    p.add_argument(
        "--data-dir",
        type=Path,
        default=Path(__file__).resolve().parent / "role_task",
        help="tasks_MM-DD.json directory (default: role_task/ under script directory)",
    )
    p.add_argument("--date", default=None, help="task date YYYY-MM-DD, default today (local)")
    p.add_argument(
        "--target",
        required=True,
        help="target role name (must match a section in commander.ini, e.g., hr)",
    )
    p.add_argument("--command", required=True, help="command line to execute on soldier (will be passed to shell)")
    p.add_argument(
        "--task-id",
        default=None,
        help="task UUID hex (8-32 chars); auto-generated by default",
    )
    p.add_argument("--task", default="", help="task text for today's task record")
    p.add_argument(
        "--description",
        default=None,
        help="(deprecated) backward-compatible alias of --task",
    )
    p.add_argument("--planned-time", default=None, help="planned task time HH:MM from unified role file")
    p.add_argument(
        "--timeout-minutes",
        type=int,
        default=10,
        help="timeout for waiting tasks in minutes (default: 10)",
    )
    p.add_argument(
        "--config",
        type=Path,
        default=None,
        metavar="PATH",
        help=f"INI config file path (default same directory as script {DEFAULT_CONFIG_NAME})",
    )
    args = p.parse_args()
    
    # Determine config file path
    cfg = args.config if args.config is not None else default_config_path()
    
    # Load target configuration
    try:
        soldier_host, soldier_port = load_target_config(cfg, args.target)
    except FileNotFoundError as e:
        # Log to stderr since logging not yet set up
        print(f"ERROR: {e}", file=sys.stderr)
        return 1
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1
    
    # Normalize target to lowercase for role name (strict matching)
    target_role = args.target.lower()
    
    logs_dir = Path(__file__).resolve().parent / "logs"
    logs_dir.mkdir(exist_ok=True)
    log_file = logs_dir / f"dispatch_{date.today().isoformat()}.log"
    
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)
    
    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.INFO)
    file_handler = logging.handlers.TimedRotatingFileHandler(
        log_file, when='midnight', interval=1, backupCount=7, encoding='utf-8'
    )
    file_handler.setLevel(logging.INFO)
    
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    console_handler.setFormatter(formatter)
    file_handler.setFormatter(formatter)
    
    logger.addHandler(console_handler)
    logger.addHandler(file_handler)
    
    logging.info(f"Dispatch starting, logs: {log_file}")

    data_dir = args.data_dir.resolve()
    repository = DailyTaskRepository(data_dir)
    if args.date:
        try:
            d = date.fromisoformat(args.date)
        except ValueError:
            logging.error("Invalid --date, must be YYYY-MM-DD")
            return 1
    else:
        d = date.today()
    date_str = d.isoformat()

    if args.task_id:
        task_id = args.task_id.strip()
        if not task_id:
            logging.error("--task-id cannot be empty")
            return 1
    else:
        task_id = uuid.uuid4().hex[:16]

    err = validate_task_id(task_id)
    if err:
        logging.error(err)
        return 1

    expiry_time = (
        datetime.now(timezone.utc) + timedelta(minutes=args.timeout_minutes)
    ).isoformat()

    task_file = repository.day_path(date_str)
    if has_waiting_tasks(repository, date_str, target_role):
        logging.warning(
            f"Role {target_role} still has waiting tasks in {task_file}, not dispatching this time"
        )
        return 2

    task_ref = f"{date_str}_{target_role}_{task_id}"
    task_text = (args.task or "").strip()
    if not task_text and isinstance(args.description, str):
        task_text = args.description.strip()

    try:
        resp = send_to_soldier(
            soldier_host,
            soldier_port,
            task_ref,
            args.command,
            date_str,
            args.planned_time,
        )
    except OSError as e:
        logging.error(f"Dispatch failed: {e}")
        return 1

    if not resp.get("ok"):
        logging.error(f"Dispatch response indicates failure: {resp.get('error', 'unknown')}")
        return 1

    append_task(
        repository,
        date_str,
        target_role,
        task_id,
        task_text,
        expiry_time,
        args.planned_time,
    )
    logging.info(f"Written to {task_file}, task_ref={task_ref}")

    print(json.dumps(resp, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
